[package]
name = "cowfact"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
reqwest = { version = "0.13", features = ["stream", "blocking", "json"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
